### ISSUE TITLE
IOS : Crash when orientation changed to landscape mode

### ISSUE THREAD

**Issue by sanju280696** [gbumps/react-native-screenguard#10]
issue in below line
[textField.layer.sublayers.firstObject addSublayer:view.layer];

**Comment by gbumps** [comment]
`[textField.layer.sublayers.firstObject addSublayer:view.layer];` No problem with this one.

Furthermore, the orientation still works fine with a little issue as image received after capture is incorrect. However, when adding the protection layer, it crashed on iOS 16.6. 

Found it, will do a hot fix immediately.

Anyway, thanks for the report!
