### ISSUE TITLE
cannot read property 'activateShield' of null

### ISSUE THREAD

**Issue by qomi-cupist** [gbumps/react-native-screenguard#16]
1. Can I just type the code together? How should I change it?

```
  useEffect(() => {
    if (Platform.OS === 'ios') {
      ScreenGuardModule?.register(
        //insert any hex color you want here, default black if null or empty
        '#000000',
        _ => {
          // .....do anything you want after the screenshot
        },
      );
    }
  }, []);

```
![KakaoTalk_Photo_2023-08-30-12-47-22](https://github.com/gbumps/react-native-screenguard/assets/113420254/76e4149a-0334-4848-84ff-0ed50e4725e0)

2. And if you want to perform this action when the capture button is clicked on a specific page.. Can I use the same as above?
When I put it in useEffect, there was an issue where a black screen was set without capturing

**Comment by gbumps** [comment]
1. have you `cd ios && pod install` yet ? Please double check `README` again to continue.
2. the module has already been registered and run until `unregisted` is called. So you just call the function just only ONCE.

`When I put it in useEffect, there was an issue where a black screen was set without capturing` -> describe your problem more detail, iOS version running, simulator, library version you are using.

**Comment by qomi-cupist** [comment]
1. yes i have `cd ios && pod install`

2. Share the device type
- ios version:  16.1.1 
- android version: 10

**Comment by qomi-cupist** [comment]
hmm... sorry 
For both 1 and 2, can android tell you that some don't? 🥲

**Comment by gbumps** [comment]
have you check this yet ?

https://github.com/gbumps/react-native-screenguard#post-installation-setting-for-android-important

if not, open Android Studio and check the module `react-native-screenguard` in the `Project` section to see if it is linked automatically yet. (i recommend to use `yarn install`  for autolinking).

I have checked on Android and still run normally. (I'm running `v.0.2.0` (latest), Android 10, react-native 0.71.8)

**Comment by meredithvf** [comment]
I am getting the same error: `cannot read property 'activateShield' of null`. I am running with expo on ios and have followed the installation & setup including `cd ios && pod install`. My react version is 0.72.6.

**Comment by gbumps** [comment]
@meredithvf  please first eject expo to continue

**Comment by antonyjo1** [comment]
The same error on Expo 51.0.26 and RN 0.74.5 IOS. On simulator everything is ok but on device shows the error.
