### ISSUE TITLE
Doesn't work with iOS full screen player

### ISSUE THREAD

**Issue by shivam-kakkar27** [gbumps/react-native-screenguard#17]
This doesn't work with react-native-video iOS full screen player. In all other cases it works perfectly. Any workaround this?

**Comment by gbumps** [comment]
I've checked the library `react-native-video` but seems like it does not provides any param or method to prevent the screenshot or screen recording. Thankfully, `AVFoundation` on iOS (the library uses this) already provides this mechanism.

I think you should clone the `react-native-video` to your own repo. After that, find somewhere in the `Video/RCTVideo.swift` the instance declaration of the `AVPlayerViewController()` and set like this: 

```_playerViewController.requiresLinearPlayback = true```

And you can use my library to show a message by using `registerWithoutScreenGuard` if you want to show a message if a screenshot or recording video was detected.

on Android, calls `register` is enough.

That's all I can provide for you.

**Comment by shivam-kakkar27** [comment]
Thanks you so much for this. I will try and let you know.
