### ISSUE TITLE
ScreenGuardModule is disabling the text inputs in the entire app in iOS

### ISSUE THREAD

**Issue by shivam-kakkar27** [gbumps/react-native-screenguard#18]
ScreenGuardModule.registerWithBlurView and other functions work properly but I'm not able to click on any input box in the app. After removing ScreenGuardModule.register functions and rebuilding the app, the text inputs become editable again.
I've tested this on both the iOS simulator and real device.

**Comment by gbumps** [comment]
Please get back to the version `v.0.1.8` as i'm finding another way to fix this.

**Comment by shivam-kakkar27** [comment]
Hey thanks. This solved the input box issue by using v0.1.8

**Comment by gbumps** [comment]
I will try to have this fixed ASAP. Apologize for any inconvenience.

**Comment by gbumps** [comment]
This issue has been resolved, please install to the latest version `v0.2.2` or `npm i react-native-screenguard@latest`. Thanks!
