### ISSUE TITLE
imageView is undeclared

### ISSUE THREAD

**Issue by iwater** [gbumps/react-native-screenguard#23]
<img width="678" alt="截屏2023-09-29 16 45 33" src="https://github.com/gbumps/react-native-screenguard/assets/108937/fdf56fa4-70f7-4d1b-a40c-6285f9cc37e8">

**Comment by gbumps** [comment]
Crunching on a fix right away, thanks for reporting!

**Comment by gbumps** [comment]
done, try version `0.2.8` please
