### ISSUE TITLE
Can secureView be applied for when user trying to record the screen ? 

### ISSUE THREAD

**Issue by mthinh** [gbumps/react-native-screenguard#38]
# What ?
Can secureView be applied for when user trying to record the screen ? 
I found that UIKit has `UIScreenCapturedDidChangeNotification` to detect where screen is started recored, while this lib only contains `UIApplicationUserDidTakeScreenshotNotification`. 
Can we add listener to detect where the screen is started being recorded ? 
Thank you @gbumps 
https://developer.apple.com/documentation/uikit/uiscreencaptureddidchangenotification

**Comment by gbumps** [comment]
Hi @mthinh
At present, all function are fully applied for both screenshot and screen recording on iOS, comes with listener as well.

Yep, you may right about the `UIScreenCapturedDidChangeNotification` and `UIApplicationUserDidTakeScreenshotNotification`. When the screen is being recorded, it's not triggered the event but screen capture only.

I'm too busy of company's stuff, I'll consider add this on the next update. Thanks for suggestion!

Or if you want to contribute, don't hesitate to create a PR and I'll check for it.

**Comment by mthinh** [comment]
Thanks for your reply @gbumps 
Just to confirm that when I start recording the screen, does the secure view appear or when only I take a screenshot when recording ?

**Comment by gbumps** [comment]
both recording and screen capture are applied, just only event listener when capturing is triggered, recording not yet.

**Comment by mthinh** [comment]
Thanks @gbumps for your help

**Comment by gbumps** [comment]
Closing. Add another TODO for this
