### ISSUE TITLE
[iOS] App crash after open webview and taking screenshot 

### ISSUE THREAD

**Issue by mthinh** [gbumps/react-native-screenguard#41]
Hi @gbumps , I face this error if you have any idea on this ? Thank you

Device: Simulator iPhone 15 pro iOS 17.0.1 
react-native-screenguard: 0.3.2

# Step to reproduce:
- register the ScreenGuardModule.register 
- open inapp webview 
- trigger screenshot 
- The screenshot is replaced by black screenshot 
- App crash with error 
```
Your app just crashed. See the error below.
NSInternalInconsistencyException: Error when sending event: onSnapper with body: (null). RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in ScreenGuard, even though it's inherited from RCTEventEmitter.
```

**Comment by gbumps** [comment]
I guess that you're using `react-native-webview` to display an in-app webview. Does it happened on real device ?

It's better to reproduce it with a recording screen instead so I can clearly understand what's happening.

**Comment by gbumps** [comment]
while I'm finding a way to fix, here's the work around for you:  Try to open the in-app Webview inside a Modal.

**Comment by gbumps** [comment]
> While I'm finding a way to fix, here's the work around for you: Try to open the in-app Webview inside a Modal.

hello @mthinh, Does this solved your problem yet ? If not, just reopen the issue.

Thanks!
