### ISSUE TITLE
Is it possible to prevent screenshots in an iOS modal when using the `presentationStyle: 'pageSheet'` option?

### ISSUE THREAD

**Issue by GokuVijay** [gbumps/react-native-screenguard#47]
I'm using the React Native Element BottomSheet component. However, when the bottom sheet is opened on iOS, it appears that the green colored screen is being pushed behind the other screens. Please provide support for this issue

    <BottomSheet
      isVisible={isVisible}
      onBackdropPress={closeDetails}
      modalProps={{
        presentationStyle: 'pageSheet',
      }}
      scrollViewProps={{ bounces: false, scrollEnabled: false }}
    >
    .....
    </BottomSheet>

<img width="366" alt="image" src="https://github.com/gbumps/react-native-screenguard/assets/84261226/2f2d2992-a63e-4d10-b71d-62228cde9af1">

**Comment by gbumps** [comment]
hi @GokuVijay, can you try using 'react-native-modal' and set bottom modal for it ?
