### ISSUE TITLE
The `registerWithBlurView` function has no callback

### ISSUE THREAD

**Issue by bricezele** [gbumps/react-native-screenguard#53]
I'd like to thank you for this amazing package.

I know that the `registerWithBlurView` function is still in beta, but it seems like for the moment the function signature doesn't allow you to add a callback as specified in the documentation. In fact, when you look at the source file in index.ts, whe have this:

```typescript
 /**
   * Activate screenshot blocking with a blur effect after captured (iOS 13+, Android 6+)
   * @param data ScreenGuardBlurDataObject data object
   * @param callback void callback after a screenshot or a video capture has been taken
   * @version v0.1.2+ (iOS)
   * @version v1.0.0+ (Android)
   */
  registerWithBlurView(data: ScreenGuardBlurDataObject)
```

The callback is not specified.

I also have this unexpected behaviour on Android,

Hhen I try to open the screen containing the screen guard, the splashscreen is displayed. Note that I use the [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash) package for the splashscreen.

https://github.com/gbumps/react-native-screenguard/assets/14944418/9539e309-49b7-4e62-a138-8df0e9b09d5f

Here is my code

```typescript
    useEffect(() => {
            ScreenGuardModule.registerWithBlurView({
                radius: 35,
                timeAfterResume: 2000,
            })
        

        return () => {
            ScreenGuardModule.unregister()
        }
    }, [])
```

My environment:

react-native: 0.73.5
react-native-screenguard: 1.0.8-beta 
Samsung Galaxy S9 
Android 10 (API 34)

**Comment by gbumps** [comment]
Hi @bricezele, thanks for reaching out. As I mentioned on latest release `0.3.6` and `1.0.8-beta`, callback has been removed, instead you must call `registerScreenshotEventListener` and `registerScreenRecordingEventListener` yourself. Please have a look here [release](https://github.com/gbumps/react-native-screenguard/releases) .\

```
/**
   * Activate screenshot blocking with a blur effect after captured (iOS 13+, Android 6+)
   * @param data ScreenGuardBlurDataObject data object
   * @param callback void callback after a screenshot or a video capture has been taken
   * @version v0.1.2+ (iOS)
   * @version v1.0.0+ (Android)
   */
```
Sure that I'll have this updated later on.

On the unexpected behavior, I cannot determine exactly based on your record. Please double-check carefully with the owner of `[react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash)` 1st. 

And please note that support for RN 0.73 still in progress and testing, not yet release.
