### ISSUE TITLE
[Android] Screenshots work under emulator

### ISSUE THREAD

**Issue by sizuf** [gbumps/react-native-screenguard#55]
Running Pixel 8 under latest MacOs. Tested on actual physical device and works as expected (prevents screenshots). 
Seems the  android emulator doesn't have a `Trigger Screenshot ` feature  :( 
Am I missing something about emulators in general?

**Comment by gbumps** [comment]
Hi @sizuf, If you want to test on Android emulator, you can create an emulator with Google Play Service API supported. Then go to Play Store and download any screen record app and screenshot app based on your need (XRecorder, AZ, etc....) for testing.

Android 12+ emulator already provided screenshot and screen record function in Quick Settings Panel.

**Comment by sizuf** [comment]
Trying exactly from the quick settings leads to that result
