### ISSUE TITLE
Missing `com.screenguard.model` in v0.3.9

### ISSUE THREAD

**Issue by pnthach95** [gbumps/react-native-screenguard#57]
I try new release but can't build because of `com.screenguard.model`. I don't see it in `android` folder.

https://github.com/gbumps/react-native-screenguard/blob/0e5da4893f8549d12757e4174ee5eb93dff5ce43/android/src/main/java/com/screenguard/ScreenGuardModule.java#L22

**Comment by gbumps** [comment]
please remove 2 lines below and rebuild. I'll have a hot fix immediately

```
import com.screenguard.model.ScreenGuardBlurData;
import com.screenguard.model.ScreenGuardImageData;
```

**Comment by gbumps** [comment]
built in `v0.4.0`. Please install and rebuild.

Thanks!.

**Comment by gbumps** [comment]
built in `v.1.0.0`, please install and rebuild

Thanks!
