### ISSUE TITLE
ios webview fullscreen video is not prevented from recording

### ISSUE THREAD

**Issue by Strate** [gbumps/react-native-screenguard#64]
Hello!
This awesome library does not prevent screen recoding when playing **fullscreen** video from react-native-webview.
All other cases seems work fine.
Could you fix it?

**Comment by Strate** [comment]
Sorry, looke like dupe #17

**Comment by gbumps** [comment]
Hi @Strate, just set `allowsFullscreenVideo={false}` on WebView component, or try to find a way to bring your logic inside React native View instead of webview for the temporary fix.

**Comment by Strate** [comment]
> Hi @Strate, just set `allowsFullscreenVideo={false}` on WebView component, or try to find a way to bring your logic inside React native View instead of webview for the temporary fix.

Thank you for advices!
