### ISSUE TITLE
Just want to use it for screen protection when the app is in the background

### ISSUE THREAD

**Issue by Unich-HieuDT** [gbumps/react-native-screenguard#65]
After declaring ScreenGuardModule.register in the root, a protection view appears. Everything works well when the app goes to the background. But the problem is I don’t want to block screenshots.
How should I handle this?

**Comment by gbumps** [comment]
Hi @Unich-HieuDT, just want to know which of of these in your concern:
1. Screenshot blocking activated, but unblock after the app goes to background. 
2. Just screenshot detector only

**Comment by Unich-HieuDT** [comment]
Hi @gbumps Thank you for your response.
I want to ensure that declaring ScreenGuardModule.register does not block screenshots.
I only want the screen to be protected when the app is in the background.

Yeah. The image below is all I want, I do not need to block screenshots.
![Simulator Screenshot - iPhone 15 Pro Max - 2024-07-09 at 17 45 49](https://github.com/gbumps/react-native-screenguard/assets/171046339/c3e5c324-ae76-4516-9fbe-6c89c9ea4c3f)

**Comment by gbumps** [comment]
If you want to block screenshot at background, you can use `AppState` of React Native, or a custom React Native library which handle and listen for the app state changed. Then handle and trigger `unregister` when app in foreground, and `register` when in background based on this example below:

```
import React, {useRef, useState, useEffect} from 'react';
import {AppState, StyleSheet, Text, View} from 'react-native';
import ScreenGuardModule from 'react-native-screenguard';

const AppStateExample = () => {
  const [appState, setAppState] = useState(AppState.currentState);

  useEffect(() => {
    const handleAppStateChange = (nextAppState) => {
      if (nextAppState === 'inactive' || nextAppState === 'background') {
        ScreenGuardModule.register();
      } else if (nextAppState === 'active') {
        console.log('foreground');
        ScreenGuardModule.unregister();
      }
      setAppState(nextAppState);
    };

    const subscription = AppState.addEventListener('change', handleAppStateChange);

    // Cleanup the subscription on unmount
    return () => {
      subscription.remove();
    };
  }, []);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Current app state is: {appState}</Text>
    </View>
  );
};

export default AppStateExample;
```

**Comment by gbumps** [comment]
You can use `AppState` of React Native, or a custom-made React Native lib which handle and listen for this event, then `register` when in background state, `unregister` on the foreground state. You can check my example below
 
```
import React, {useRef, useState, useEffect} from 'react';
import {AppState, StyleSheet, Text, View} from 'react-native';
import ScreenGuardModule from 'react-native-screenguard';

const AppStateExample = () => {
  const [appState, setAppState] = useState(AppState.currentState);

  useEffect(() => {
    const handleAppStateChange = (nextAppState) => {
      if (nextAppState === 'inactive' || nextAppState === 'background') {
        ScreenGuardModule.register();
      } else if (nextAppState === 'active') {
        console.log('foreground');
        ScreenGuardModule.unregister();
      }
      setAppState(nextAppState);
    };

    const subscription = AppState.addEventListener('change', handleAppStateChange);

    return () => {
      subscription.remove();
    };
  }, []);

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Text>Current app state is: {appState}</Text>
    </View>
  );
};

export default AppStateExample;
```

**Comment by Unich-HieuDT** [comment]
Hi @gbumps Thank you for providing a solution.
It works very well on iOS, but not on Android. After ScreenGuardModule.unregister when the app goes to active, the AppState status falls into an infinite loop (see image below).
Is there a way to solve this problem on Android?
<img width="171" alt="Screenshot 2024-07-11 at 00 45 27" src="https://github.com/gbumps/react-native-screenguard/assets/171046339/0633529e-375f-4210-b6a8-6cd0320f0e55">

**Comment by gbumps** [comment]
i think with Android on this case,  you can use `registerWithoutEffect` instead

**Comment by Unich-HieuDT** [comment]
Oh, thank you. It seems to be working quite well.
But it goes back to the initial issue: Even though I have already unregister(), it seems like the app is still blocking screenshots.
![Screenshot_1720635788](https://github.com/gbumps/react-native-screenguard/assets/171046339/3311991c-62c5-41f9-95d6-14251937743f)

**Comment by gbumps** [comment]
the app is still in inactive state based on the image you provide

**Comment by gbumps** [comment]
Hi @Unich-HieuDT, I have not received the answer yet. So I suggest you should call `unregister` on unmounting also for sure.

**Comment by Unich-HieuDT** [comment]
Hi @gbumps Thank you for your feedback. It seems like I’ve resolved all the issues.

**Comment by a-raosaheb-gunjal** [comment]
@gbumps is this working for android as well?

**Comment by gbumps** [comment]
@a-raosaheb-gunjal  yes, just follow up [here](https://gbumps.github.io/react-native-screenguard/docs/testing) on how to set up and testing on Android emulator
