### ISSUE TITLE
Crash when using registerWithImage with a local image source

### ISSUE THREAD

**Issue by RikSchefferAmsterdam** [gbumps/react-native-screenguard#66]
My app crashes when I call registerWithImage with a local image source.
For example this code causes the crash:
```ts
import ScreenGuard from 'react-native-screenguard'

...

ScreenGuard.registerWithImage({
  backgroundColor: '#ff0000',
  defaultSource: require('./bootsplash_logo.png') as number,
  source: require('./bootsplash_logo.png') as number,
  height: 120,
  width: 244,
})
```
When changing it to this the crash disappears:
```ts

import ScreenGuard from 'react-native-screenguard'
import {  resolveAssetSource,} from 'react-native-screenguard/src/main/constant'

...

ScreenGuard.registerWithImage({
  backgroundColor: '#ff0000',
  defaultSource: require('./bootsplash_logo.png') as number,
  source: {
    uri: resolveAssetSource(
      require('./bootsplash_logo.png') as number,
    ) as string,
  },
  height: 120,
  width: 244,
})
```

I managed to fix it by making a change in the library by ging it a default value for the defaultSource in react-native-screenguard/src/commonjs/index.js:
```ts
let newDefaultSource = {
            uri: ScreenGuardConstants.resolveAssetSource(defaultSource),
        };
```
Also the checks for an existing default source are missing from the case `typeof source === 'number'`.

I only tested this on iOS.

**Comment by gbumps** [comment]
on which react-native version, iOS, Android version ? Please be more specifics.

**Comment by RikSchefferAmsterdam** [comment]
react-native: 0.74.3
iOS: 17.5.1

**Comment by gbumps** [comment]
Why need to try-parse to `number` ? I think this could be the crash.

**Comment by RikSchefferAmsterdam** [comment]
the `as number` bit is just typescript, it does not change anything functional, crash also persist without the `as number`
