### ISSUE TITLE
App.tsx

### ISSUE THREAD

**Issue by uselesstester** [gbumps/react-native-screenguard#7]
Any way you could please upload the project you show on the videos on the README?
I don't see that app.tsx anywhere in the files.

Thank you :D

**Comment by uselesstester** [comment]
Yeah, i dont see the /example folder anywhere, I am not looking in the right place or what am I doing wrong?

**Comment by gbumps** [comment]
thanks for the issue. I will update shortly

**Comment by gbumps** [comment]
Hello, I've updated the example at this commit.

https://github.com/gbumps/react-native-screenguard/commit/6171336328d085a34b6b798ffbf4f33c6bf8e359

Closing this issue as completed.
