### ISSUE TITLE
[BUG] Black screen when calling register method on Android

### ISSUE THREAD

**Issue by gfroidcourt** [gbumps/react-native-screenguard#70]
Hello,

I'm using `react-native` (version 0.73.6) with `expo` (SDK 50) and I have a bug on android Pixel 8 emulator, with Android 14.0 and Android SDK 35. 

When I call the `register`function from `ScreenGuardModule`, i'm getting a totally black screen on my emulator (check screenshot below)

The code is as follow:
```ts
 useEffect(() => {
    ScreenGuardModule.register({
      backgroundColor: COLORS.tango,
    });
    return () => {
      ScreenGuardModule.unregister();
    };
  });
```

![image](https://github.com/user-attachments/assets/1275980d-72ad-4899-8280-a73ed493d4b5)

Am I doing something wrong ?

**Comment by gbumps** [comment]
Have you eject the Expo module or running `npx expo prebuild` yet ?

Can you show me the value of the Colors.TANGO ?

Try running on a bare React-native project too see if problem happened

**Comment by gfroidcourt** [comment]
I ran `npx expo prebuild` right after the installation.

For the Colors.TANGO value, it is as follow: `#EB6214`.

Last, I experience the same issue in a bare React-native project. 

I did:

`npx @react-native-community/cli@latest init AwesomeProject`
`npm install react-native-screenguard --save`

Then, in `App.tsx`:

```ts
useEffect(() => {
    ScreenGuardModule.register({
      backgroundColor: '#EB6214',
    });
    return () => {
      ScreenGuardModule.unregister();
    };
  });
```

And same, a black screen when the app opens.

**Comment by gbumps** [comment]
Are there any problems when using `registerWithoutEffect` ? If not, i suggest you should use `registerWithoutEffect` as a temporary solution for Android 15 while I'm discovering this issue. This might be happened on Android 15, below not detected yet.

Anyway, thanks for reporting.

**Comment by gfroidcourt** [comment]
I don't get the black screen using `registerWithoutEffect`. But when I try to do a screenshot, it doesn't block anything. Same for screen recording

**Comment by gbumps** [comment]
Please refer [here](https://gbumps.github.io/react-native-screenguard/docs/testing/) on how to test on the Emulator on both platforms 1st.

**Comment by gbumps** [comment]
Hi @gfroidcourt, try to go to `{your_project}/android/build.gradle` and change the `compileSdkVersion` and  `targetSdkVersion` to 33 and rebuild again, as 34 has some issue which caused the black screen happened.

**Comment by gfroidcourt** [comment]
Sadly, I can't downgrade `compiledSdkVersion` and `targetSdkVersion` to 33 because I have packages that depends on sdk 34. 
However, I tried the downgrade in a bare React-native project and I noticed that the `registerWithoutEffect` works while I'm recording the screen with `XRecorder`, but doesn't works when I'm taking screenshot with the Quick Settings Panel.

**Comment by gbumps** [comment]
Can you test on real device to see if problem persists ?

**Comment by gbumps** [comment]
If you've run the project expo build successfully but encountered black screen, you might have forgot this step [here](https://gbumps.github.io/react-native-screenguard/docs/getting-started/linking#post-installation-for-android)

**Comment by gbumps** [comment]
If you've run the project expo build successfully but encountered black screen, you might have forgot this step [here](https://gbumps.github.io/react-native-screenguard/docs/getting-started/linking#post-installation-for-android).

Please revise document, adapt, clean and built project again.

```
...but doesn't works when I'm taking screenshot with the Quick Settings Panel.
```
Please show me how you test this on Android Emulator. I've tested `registerWithoutEffect` on both Android real device and emulator, all still works fine though.

**Comment by gbumps** [comment]
Hi @gfroidcourt, have you solved the problem yet ? You can reopen this issue again if need

Thanks and happy hacking!

**Comment by levepic** [comment]
Still an issue

**Comment by gbumps** [comment]
@levepic please try to add up a little bit configuration in [this](https://gbumps.github.io/react-native-screenguard/docs/getting-started/linking#post-installation-for-android) example here and try again.

**Comment by levepic** [comment]
That works perfectly, thank you, although in the docs a bit hidden under RN 0.59 linking guide, i suggest to place it up front and not under Linking

**Comment by gbumps** [comment]
> That works perfectly, thank you, although in the docs a bit hidden under RN 0.59 linking guide, i suggest to place it up front and not under Linking. Also I had to switch to registerWithoutEffect

Thanks for the suggestion, I'll consider it on the upcoming version.

**Comment by deepktp** [comment]
i have also encountered the same issue.
i was trying to prevent screenshots on only on specific screen only and allow on all other screens.

### Verisons: 
react-native  : 75.2
@react-navigation/native-stack:  6.11.0
react-native-screenguard: 1.0.2

### Device
Testing device - Android 14 (Physical Samsung device)

## Steps to reproduce

1. Added 2 buttons on a screen on to with register (empty object passed) and other to unregister 
2.  if we press register button once and it works fine no crash and system message about screen shot not allowed if we try to take screen shot. 


**issue 1.** when we press on register  twice screen become black. if we press on back button of hardware app just crash (even if there is a screen to go back in navigation)

**issue2.** after register even if we press on unregister we can't take screen shots 


### it works fine with registerWithoutEffect and also unregister works too.


### Logcat log in case of calling register twice (Not sure about this i don't have much knowledge about adb or native codes)

> 10-16 11:31:24.696 14844 14844 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {com.srjajoriya/com.screenguard.ScreenGuardColorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5780)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5731)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5683)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:230)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:319)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8919)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.graphics.Color.parseColor(Color.java:1383)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at com.screenguard.ScreenGuardColorActivity.doCoverByAction(ScreenGuardColorActivity.java:200)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at com.screenguard.ScreenGuardColorActivity.onPause(ScreenGuardColorActivity.java:111)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.Activity.performPause(Activity.java:9188)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1657)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5770)
> 10-16 11:31:24.696 14844 14844 E AndroidRuntime:        ... 14 more

**Comment by ricophie03** [comment]
Hello, I'm having the same issue of black screen in android when using registerWithImage. I'm currently using react native version 0.72.7 and my sdk version is 34. Cannot be downgrade, some package need to be this version.

**Comment by gbumps** [comment]
@ricophie03 please check this and try again [reference](https://github.com/gbumps/react-native-screenguard/issues/70#issuecomment-2385515669)

**Comment by thibaultcapelli** [comment]
@deepktp Did you find a fix for this. I also can use registerWithoutEffect without any issue so I had to switch to it for now
