### ISSUE TITLE
ContextCompat.RECEIVER_NOT_EXPORTED Compilation Error in Version 1.0.2

### ISSUE THREAD

**Issue by crazywook** [gbumps/react-native-screenguard#72]
I recently updated react-native-screenguard from version 1.0.0 to 1.0.2. After the update, I encountered a compilation error related to ContextCompat.RECEIVER_NOT_EXPORTED in the ScreenGuardColorActivity.java file. This issue did not occur in version 1.0.0.

- Error Detail
```
Task :react-native-screenguard:compileReleaseJavaWithJavac FAILED
/Users/sungwookkim/workspace/supplies/gymboxx-app-client/node_modules/react-native-screenguard/android/src/main/java/com/screenguard/ScreenGuardColorActivity.java:95: error: cannot find symbol
registerReceiver(closeReceiver, intentFilter, ContextCompat.RECEIVER_NOT_EXPORTED);
^
symbol:   variable RECEIVER_NOT_EXPORTED
location: class ContextCompat
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

Please let me know if there is any other recommended solution or if this can be fixed in the next release.

Thank you for your assistance.

**Comment by ZouwenSB** [comment]
I also have this issue, for me the fix was to pin it to 1.0.0 for now. Hope it still will be fixed

**Comment by gbumps** [comment]
hi @crazywook, working on it, will have a release soon.

You can also fix it yourself by opening Android studio, and go to `react-native-screenguard/java/com/screenguard/ScreenGuardColorActivity.java`, line 94, and change like this:

```
...
 registerReceiver(closeReceiver, intentFilter, RECEIVER_NOT_EXPORTED);
...
```
thanks and happy hacking !

**Comment by Inayat567** [comment]
go to react-native-screenguard/java/com/screenguard/ScreenGuardColorActivity.java, line 94, 
patch the package 


    IntentFilter intentFilter = new IntentFilter(SCREENGUARD_COLOR_ACTIVITY_CLOSE);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) { // Android 13+
            registerReceiver(closeReceiver, intentFilter, Context.RECEIVER_NOT_EXPORTED);
        } else {
            registerReceiver(closeReceiver, intentFilter);
        }
        
I have fixed this issue by apply above patch
