### ISSUE TITLE
Screen is gaurded when it is not supposed to

### ISSUE THREAD

**Issue by faljabi** [gbumps/react-native-screenguard#80]
Hello, I am facing an issue that the library is considering the screen as being recorded or screen captured whenever I open an external link or for example using the Linking API such as:

```
Linking
                .openURL(Platform.select({
                    ios: Config.IOS_APP_STORE_WRITE_REVIEW_URL,
                    android: Config.ANDROID_PLAY_STORE_WRITE_REVIEW_URL
                }))
```

I am using registerWithImage as shown below:

```
ScreenGuard.registerWithImage({
                height: 96,
                width: 96,
                source: LogoDark,
                defaultSource: LogoDark,
                alignment: 4
            });
```

I do not want to have the screen guarded for such scenario. I attached a video showing the black screen registered with Image.
How to resolve this please?

https://github.com/user-attachments/assets/cc9cd2a4-3165-4b82-83ae-241c95daa38b

**Comment by faljabi** [comment]
Updated: I solved it by using appState similar to what was explained here

https://github.com/gbumps/react-native-screenguard/issues/65

**Comment by gbumps** [comment]
hi @faljabi, nice to see it worked normally. If you have any issue or PR just let me know.

Thanks and happy hacking!
